### ISSUE TITLE
Resource Utilization Error when building large-scale AGFI

### ISSUE THREAD

**Issue by aladerran** [firesim/firesim#1693]
### Background Work

- [X] Yes, I searched the [mailing list](https://groups.google.com/forum/#!forum/firesim)
- [X] Yes, I searched [prior issues](https://github.com/firesim/firesim/issues)
- [X] Yes, I searched the [documentation](https://docs.fires.im/en/stable/)

### FireSim Version and Hash

1.17.1-1-g9d8a5be32

### OS Setup

```
<!-- copy/paste the output of `uname -a; lsb_release -a` below -->
Linux ip-192-168-0-189.ec2.internal 3.10.0-1160.81.1.el7.x86_64 #1 SMP Fri Dec 16 17:29:43 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.9.2009 (Core)
Release:        7.9.2009
Codename:       Core
```

### Current Behavior

Hi all,

I have a multi-core SoC design that may be too large to fit into a F1 FPGA for firesim-  I met ```Resource (over-)Utilization``` error when trying to build the following SoC w\ 4 LagreBoom + Gemmini.

```
firesim_custom_gemmini_soc_no_nic_l2_llc4mb_ddr3:
    PLATFORM: f1
    TARGET_PROJECT: firesim
    DESIGN: FireSim
    TARGET_CONFIG: DDR3FRFCFSLLC4MB_WithDefaultFireSimBridges_WithFireSimTestChipConfigTweaks_chipyard.CustomQuadBoomGemminiSoCConfig 
    PLATFORM_CONFIG: WithAutoILA_BaseF1Config
    deploy_quintuplet: null
    platform_config_args:
        fpga_frequency: 30
        build_strategy: TIMING
    post_build_hook: null
    metasim_customruntimeconfig: null
    bit_builder_recipe: bit-builder-recipes/f1.yaml
```

```
class CustomQuadBoomGemminiSoCConfig extends Config(
  new gemmini.GemminiCustomConfig ++

  // Set your custom L2 configs
  new chipyard.config.WithL2TLBs(512) ++

  new freechips.rocketchip.subsystem.WithInclusiveCache(
    nWays = 8,
    capacityKB = 512,
    outerLatencyCycles = 40,
    subBankingFactor = 4
  ) ++

  // Set the number of CPUs you want to create
  new chipyard.CustomGemmminiCPUConfigs.CustomCPU(4) ++

  new chipyard.config.WithSystemBusWidth(GemminiCustomConfigs.customConfig.dma_buswidth) ++
  new chipyard.config.AbstractConfig
)
```

Error log: 
[2024-02-03--02-29-25-buildbitstream-XGMR35ECBNDGHYS3.log](https://github.com/ucb-bar/gemmini/files/14150487/2024-02-03--02-29-25-buildbitstream-XGMR35ECBNDGHYS3.log)

I wonder if there is any approaches to enlarge the capacity of a single FPGA now. 
Also, the methods in https://docs.fires.im/en/latest/Golden-Gate/Resource-Optimizations.html seem to help with multi-core booms, but it may not be sufficient since I want to enlarge the SRAM of Gemmini size later.

Looking forward to your reply!

### Expected Behavior

Generate an AGFI successfully.
