### ISSUE TITLE
Error with bcrypt during aws setup

### ISSUE THREAD

**Issue by hyuns-lee** [firesim/firesim#1831]
### Background Work

- [X] Yes, I searched the [mailing list](https://groups.google.com/forum/#!forum/firesim)
- [X] Yes, I searched [prior issues](https://github.com/firesim/firesim/issues)
- [X] Yes, I searched the [documentation](https://docs.fires.im/en/stable/)

### FireSim Version and Hash

1.20.1-0-g12e2e0a6b

### OS Setup

Linux ip-192-168-0-73.us-west-2.compute.internal 3.10.0-1160.81.1.el7.x86_64 #1 SMP Fri Dec 16 17:29:43 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.9.2009 (Core)
Release:	7.9.2009
Codename:	Core

### Other Setup

I followed firesim doc v1.20.1 and latest
(https://docs.fires.im/en/1.20.1/Getting-Started-Guides/AWS-EC2-F1-Getting-Started/index.html#aws-ec2-f1-getting-started-guide)

### Current Behavior

After completing the machine launch script, I cloned Firesim version 1.20.1 and executed ./build-setup.sh.
However, I encountered an error related to bcrypt, preventing me from completing the setup.
I faced the same issue when attempting to set up the latest Firesim repository by first cloning Chipyard.
I also attempted to set up firesim versions 1.17 through 1.19, but it seems there are issues related to CentOS reaching its end of support.

### Expected Behavior

The bcrypt package in conda-reqs/conda-reqs.conda-lock.yml may need to be updated to ensure compatibility with Python 3.9.
```
- name: bcrypt
  version: 4.2.0
  manager: pip
  platform: linux-64
  dependencies: {}
  url: https://files.pythonhosted.org/packages/3e/d0/31938bb697600a04864246acde4918c4190a938f891fd11883eaaf41327a/bcrypt-4.2.0-cp39-abi3-manylinux_2_28_x86_64.whl
  hash:
    sha256: 3d3a6d28cb2305b43feac298774b997e372e56c7c7afd90a12b3dc49b189151c
  category: main
  optional: false
```
I want to know how can I fix conda-lock.yml file
